### ISSUE TITLE
Morning session: peer-to-peer code reviews 20/01/2023

### ISSUE THREAD

**Issue by flemton** [NelsonAraujo93/toDoList#8]
# Peer to peer code review in module 2 week 3

## Highlights 
- Good commit messages ✔️ 
- Clean code ✔️ 
- Nice README ✔️ 
### Everything works as expected and everything looks clean and follows GitHub flow, but it would be nice if unwanted comments and texts could be removed from the READme to make it look even cleaner.
__Cheers and happy coding 🥂__

**Comment by NelsonAraujo93** [comment]
Thanks for the feedback
